import Head from "next/head";
import Cards from "../components/cards/Cards";
import Gigant from "../components/Gigant";
import Hero from "../components/Hero";
import Navbar from "../components/Header/Navbar";
import BottomFooter from "../components/SecondLast/Index";
import styles from "../styles/Home.module.css";
import Slider from "../components/Slider";
import SliderSec from "../components/SliderSec";

export default function Home() {
    return (
        <>
            <Head>
                <title>AUTO GIGANT</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />

                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* sections */}
            <Hero />
            {/* <Cards/> */}
            <Slider />
            {/* <SliderSec /> */}
            <Gigant />
            <BottomFooter />
        </>
    );
}
